### ISSUE TITLE
1.9.4-1.0.3-14 Overlay doesn't update

### ISSUE THREAD

**Issue by kreezxil** [SilentChaos512/HealthBar#1]
The overlay always shows 20/20 and the red meter stays full. It never goes down and the numbers never decrement. You can see the hearts in the background changing however.

**Comment by SilentChaos512** [comment]
Are you playing singleplayer or on a server? The mod doesn't work right if it's not on the server side. Also, have you changed the config file at all?

**Comment by kreezxil** [comment]
I had no idea it was meant to be on the server. I felt like a client side only mod. Yeah, playing on a server. Might want to add that it needs to be on both client and server.

**Comment by SilentChaos512** [comment]
I thought I mentioned that on the CurseForge page, looks like I didn't. Oops. It needs to be on the server to get the player's actual max health, which doesn't sync with the client sometimes (it just assumes it's 20). Still, I should probably make it so it will work client-side only as well.
