### ISSUE TITLE
more of a request

### ISSUE THREAD

**Issue by unmellow** [SilentChaos512/HealthBar#5]
could you add options for different looking health bars? for example one that looks more cartoon-ish

**Comment by SilentChaos512** [comment]
Should already be doable with a resource pack. I'm not much of an artist though.

**Comment by unmellow** [comment]
OK thanks i was using a 8x texture pack and it looked weird for suck a high res health bar to be there i guess i will have to ask someone two add a texture for your bar to it for me thanks
